environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"

install:
  - cinst hg
  - cinst git
  - "%PYTHON%\\python.exe -m pip install pytest"

build: off

test_script:
  - "%PYTHON%\\Scripts\\pytest.exe"
